### ISSUE TITLE
www.celltypist.org is down, cannot download models

### ISSUE THREAD

**Issue by sztankatt** [Teichlab/celltypist#116]
Hi, 

Thanks a lot for this amazing package!

As of this morning, I noticed that my notebooks are not working anymore, specifically I am unable to download models.

I get the following exception:
`Exception: 🛑 Cannot fetch 'https://celltypist.cog.sanger.ac.uk/models/models.json', the error is: 503 Server Error: Service Unavailable for url: https://celltypist.cog.sanger.ac.uk/models/models.json`

Upon visiting https://www.celltypist.org it seems that the whole website is down.

Best regards,
Tamas

**Comment by prete** [comment]
Hi @sztankatt thank you for using CellTypist. There is an isssue this morning with the Sanger service that hosts those files. It's being worked on and will hopefully be back soon.

**Comment by sztankatt** [comment]
Hi @prete thank you a lot for the prompt response :) The website is back now, I am closing this issue. Thank you again.

**Comment by Urja25** [comment]
Hi, I am still facing the same error. 

Cannot fetch 'https://celltypist.cog.sanger.ac.uk/models/models.json', the error is: HTTPSConnectionPool(host='celltypist.cog.sanger.ac.uk', port=443): Max retries exceeded with url: /models/models.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc31705b5b0>, 'Connection to celltypist.cog.sanger.ac.uk timed out. (connect timeout=30)'))
