### ISSUE TITLE
conda version is out of date.

### ISSUE THREAD

**Issue by bioworker** [Teichlab/celltypist#56]
Celltypist in conda is out of date (2023-2-9), methods like extract_top_markers is not in the conda version. Thanks for the nice work.

**Comment by ChuanXu1** [comment]
@bioworker, as I have tested, conda will install the newest version. You can paste your installation information here if you still fail to install the newest CellTypist.

**Comment by bioworker** [comment]
> @bioworker, as I have tested, conda will install the newest version. You can paste your installation information here if you still fail to install the newest CellTypist.

Ok, The version information suggested the newest one (1.3.0), but it lack the methods like extract_top_markers, did you check this method? Now I have reinstalled it by pip command, everything is fine now.

**Comment by prete** [comment]
Can confirm that latest conda-installed version is working.

Instaled using:
```bash
conda install -c bioconda -c conda-forge celltypist
```

Then:
```python
>>> import celltypist
>>> celltypist.__version__
'1.3.0'
>>> model = celltypist.models.Model.load(model = 'Immune_All_Low.pkl')
>>> model.extract_top_markers("Mast cells", 3)
array(['CPA3', 'TPSAB1', 'FTH1'], dtype=object)
```

**Comment by benemead** [comment]
Hi there - I also encountered this issue, but I believe it's Mac apple silicon dependent. when I run: 
`conda install -c bioconda -c conda-forge celltypist`
My install completes, but to 0.1.9, when I run:
`conda install -c bioconda -c conda-forge celltypist=1.3`
I get the following solve error:
`Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__unix==0=0
  - celltypist=1.3 -> click[version='>=7.1.2'] -> __unix
  - celltypist=1.3 -> click[version='>=7.1.2'] -> __win

Your installed version is: 0`

**Comment by prete** [comment]
Indeed it seems to be a Mac M1/M2 issue. The arm architecture probably has conflicting packages.

To solve this issue they can try rosetta. Useful links [here](https://apple.stackexchange.com/questions/409746/run-everything-in-rosetta-2-on-silicon-mac) and [here](https://www.bigbinary.com/books/learn-rubyonrails-book/setting-up-mac). Rosetta should translate intel instructions and if they are using conda, they should make sure that the right conda installer (ARM version) is used. The info in [this issue](https://github.com/numpy/numpy/issues/17807) can also help.

Otherwise, and as you mentioned, sticking with pip should not give you any issues.
