### ISSUE TITLE
Loading custom model

### ISSUE THREAD

**Issue by auesro** [Teichlab/celltypist#60]
Dear celltypist team,

I have created my own model through training using `celltypist.train`, saved it to a local folder with `model.write` but now, I don't seem to be able to load it with `models.Model.load`  even if I pass the full path to it...

```
models.Model.load('/home/auesro/Desktop/Atlas/For_Celltypist_Training/Celltypist_model_AllCells_v1.pkl')
Traceback (most recent call last):

  File "/tmp/ipykernel_149219/1064720094.py", line 1, in <module>
    models.Model.load('/home/auesro/Desktop/ Atlas/For_Celltypist_Training/Celltypist_model_AllCells_v1.pkl')

  File "/home/auesro/mambaforge/envs/Scanpy_R/lib/python3.7/site-packages/celltypist/models.py", line 90, in load
    if model in get_all_models():

  File "/home/auesro/mambaforge/envs/Scanpy_R/lib/python3.7/site-packages/celltypist/models.py", line 359, in get_all_models
    download_if_required()

  File "/home/auesro/mambaforge/envs/Scanpy_R/lib/python3.7/site-packages/celltypist/models.py", line 370, in download_if_required
    if len([m for m in os.listdir(models_path) if m.endswith(".pkl")]) == 0:

FileNotFoundError: [Errno 2] No such file or directory: '/home/auesro/.celltypist/data/models'
```

What is going on? I dont understand why is it not looking for it in the correct path I provided...

Thanks,

A

**Comment by auesro** [comment]
Solved it by changing: `models.models_path` to my local folder

**Comment by dstueckm** [comment]
Just wanted to re-raise this issue since I had the same problem and it took me quite a while to figure it out.
I am running CellTypist on a cluster, and my default model path is 
"/cluster/home/user/.celltypist/data/models"
My output (including models) are stored in a project directory, under 
"/cluster/projects/projectname/CellTypist/models"
When I specify the full filepath to a pre-trained model (e.g., with celltypist.models.Model.load()), I get the message "No available models, Downloading..." and celltypist attempts to download models. This is only resolved by changing models.models_path to my project folder. 
A possible solution might be inferring the appropriate models.models_path from the filename?

Thank you,
Daniel

**Comment by ChuanXu1** [comment]
@dstueckm, do you mind pasting your complete error message here?

**Comment by ChuanXu1** [comment]
This should have been solved now.
