### ISSUE TITLE
impatiently waiting for V2 (but very excited)

### ISSUE THREAD

**Issue by mjstrumillo** [Teichlab/celltypist#74]
Hi, I know Im jumping the gun, but Im really excited for the V2! any news on the timeframe? 
(Im assuming that's tied with the publication, but do you think its days or months?) 
MJ

**Comment by ChuanXu1** [comment]
Hi MJ, thank you for your intertest in CellTypist. Most functions from v2 are already in place in the newest v1.5.2; you can try that.

**Comment by ChuanXu1** [comment]
Due to some considerations, we have isolated the harmonization and integration modules into a separate tool [CellHint](https://github.com/Teichlab/cellhint), and now CellTypist will be retained as a cell-type-classification-focused tool. If you still have any questions, please refer to CellHint repo, open an issue or let us know.
